### ISSUE TITLE
Use kk to delete node, it report a panic runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hellocn9** [kubesphere/kubekey#1312]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.1.1", GitCommit:"b19724c7", GitTreeState:"", GoVersion:"go1.17.10"}

### What is your os environment?

CentOS 7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: k8s-cluster
spec:
  controlPlaneEndpoint:
    address: ''
    domain: lb.kubernetes.local
    internalLoadbalancer: haproxy
    port: 6443
  etcd:
    type: kubekey
  hosts:
    - address: 192.168.239.138
      arch: amd64
      internalAddress: 192.168.239.138
      name: 192-168-239-138
      password: root
      port: 22
      timeout: 60
      user: root
    - address: 192.168.239.139
      arch: amd64
      internalAddress: 192.168.239.139
      name: 192-168-239-139
      password: root
      port: 22
      timeout: 60
      user: root
    - address: 192.168.239.140
      arch: amd64
      internalAddress: 192.168.239.140
      name: 192-168-239-140
      password: root
      port: 22
      timeout: 60
      user: root
    - address: 192.168.239.141
      arch: amd64
      internalAddress: 192.168.239.141
      name: 192-168-239-141
      password: root
      port: 22
      timeout: 60
      user: root
  kubernetes:
    apiserverCertExtraSans:
      - aaa.com
      - bbb.com
    autoRenewCerts: false
    clusterName: cluster.local
    containerManager: docker
    ipv6NodeCidrMaskSize: 120
    maxPods: 110
    nodeCidrMaskSize: 24
    nodelocaldns: true
    proxyMode: ipvs
    version: v1.23.6
  network:
    kubePodsCIDR: 10.224.0.0/16
    kubeServiceCIDR: 10.19.0.0/16
    plugin: calico
  registry:
    auths:
      '192.168.239.130:5000':
        plainHTTP: true
        skipTLSVerify: true
    insecureRegistries:
      - '192.168.239.130:5000'
    namespaceOverride: google_containers
    privateRegistry: '192.168.239.130:5000'
    registryMirrors:
      - 'https://ustc-edu-cn.mirror.aliyuncs.com'
  roleGroups:
    worker:
      - 192-168-239-141
    master:
      - 192-168-239-138
      - 192-168-239-139
      - 192-168-239-140
    etcd:
      - 192-168-239-138
      - 192-168-239-139
      - 192-168-239-140
  system:
    ntpServers:
      - 192-168-239-138
    timezone: Asia/Shanghai
```

### A clear and concise description of what happend.

Use above kubekey config file to execute "./kk delete node 192-168-239-141 -f k8s.yaml --debug", it will report a panic runtime error.

### Relevant log output

```shell
bash-5.1# ./kk delete node 192-168-239-141 -f ./config/k8s.yaml --debug -y


 _   __      _          _   __           
| | / /     | |        | | / /           
| |/ / _   _| |__   ___| |/ /  ___ _   _ 
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

11:20:30 UTC [GreetingsModule] Greetings
11:20:31 UTC command: [192-168-239-141]
sudo -E /bin/bash -c "echo 'Greetings, KubeKey!'"
11:20:31 UTC stdout: [192-168-239-141]
Greetings, KubeKey!
11:20:31 UTC message: [192-168-239-141]
Greetings, KubeKey!
11:20:31 UTC command: [192-168-239-139]
sudo -E /bin/bash -c "echo 'Greetings, KubeKey!'"
11:20:31 UTC stdout: [192-168-239-139]
Greetings, KubeKey!
11:20:31 UTC message: [192-168-239-139]
Greetings, KubeKey!
11:20:31 UTC command: [192-168-239-138]
sudo -E /bin/bash -c "echo 'Greetings, KubeKey!'"
11:20:31 UTC stdout: [192-168-239-138]
Greetings, KubeKey!
11:20:31 UTC message: [192-168-239-138]
Greetings, KubeKey!
11:20:32 UTC command: [192-168-239-140]
sudo -E /bin/bash -c "echo 'Greetings, KubeKey!'"
11:20:32 UTC stdout: [192-168-239-140]
Greetings, KubeKey!
11:20:32 UTC message: [192-168-239-140]
Greetings, KubeKey!
11:20:32 UTC success: [192-168-239-141]
11:20:32 UTC success: [192-168-239-139]
11:20:32 UTC success: [192-168-239-138]
11:20:32 UTC success: [192-168-239-140]
11:20:32 UTC [DeleteNodeConfirmModule] Display confirmation form
Are you sure to delete this node? [yes/no]: yes
11:20:33 UTC success: [LocalHost]
11:20:33 UTC [ModifyConfigModule] Modify the KubeKey config file
11:20:33 UTC success: [LocalHost]
11:20:33 UTC [CompareConfigAndClusterInfoModule] Find the differences between config and cluster node info
11:20:34 UTC command: [192-168-239-138]
sudo -E /usr/local/bin/kubectl get nodes | grep -v NAME | grep -v 'master' | awk '{print $1}'
11:20:34 UTC stdout: [192-168-239-138]
192-168-239-141
11:20:34 UTC stdout: [192-168-239-138]
192-168-239-141
11:20:34 UTC success: [192-168-239-138]
11:20:34 UTC skipped: [192-168-239-139]
11:20:34 UTC skipped: [192-168-239-140]
11:20:34 UTC [DeleteKubeNodeModule] Node safely evict all pods
11:20:34 UTC command: [192-168-239-138]
sudo -E /bin/bash -c "/usr/local/bin/kubectl drain 192-168-239-141 --delete-emptydir-data --ignore-daemonsets"
11:20:34 UTC stdout: [192-168-239-138]
node/192-168-239-141 cordoned
WARNING: ignoring DaemonSet-managed Pods: kube-system/calico-node-xvbmc, kube-system/kube-proxy-728gb, kube-system/nodelocaldns-7p7dg
node/192-168-239-141 drained
11:20:34 UTC stdout: [192-168-239-138]
node/192-168-239-141 cordoned
WARNING: ignoring DaemonSet-managed Pods: kube-system/calico-node-xvbmc, kube-system/kube-proxy-728gb, kube-system/nodelocaldns-7p7dg
node/192-168-239-141 drained
11:20:34 UTC success: [192-168-239-138]
11:20:34 UTC skipped: [192-168-239-139]
11:20:34 UTC skipped: [192-168-239-140]
11:20:34 UTC [DeleteKubeNodeModule] Delete the node using kubectl
11:20:34 UTC command: [192-168-239-138]
sudo -E /bin/bash -c "/usr/local/bin/kubectl delete node 192-168-239-141"
11:20:34 UTC stdout: [192-168-239-138]
node "192-168-239-141" deleted
11:20:34 UTC stdout: [192-168-239-138]
node "192-168-239-141" deleted
11:20:34 UTC success: [192-168-239-138]
11:20:34 UTC skipped: [192-168-239-139]
11:20:34 UTC skipped: [192-168-239-140]
11:20:34 UTC close connection 192-168-239-138
11:20:34 UTC close connection 192-168-239-139
11:20:34 UTC close connection 192-168-239-140
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x70a2e7]

goroutine 1 [running]:
github.com/kubesphere/kubekey/pkg/core/connector.(*Dialer).Close(0xc00018cc30, {0x0, 0x0})
        /usr/src/myapp/pkg/core/connector/dialer.go:64 +0x27
github.com/kubesphere/kubekey/pkg/core/pipeline.(*Pipeline).Start(0xc0003b43f0)
        /usr/src/myapp/pkg/core/pipeline/pipeline.go:99 +0x3d4
github.com/kubesphere/kubekey/pkg/pipelines.DeleteNodePipeline(0xc0004538c0)
        /usr/src/myapp/pkg/pipelines/delete_node.go:43 +0x258
github.com/kubesphere/kubekey/pkg/pipelines.DeleteNode({{0x7ffd35595c59, 0xf}, {0x7ffd35595c6c, 0x11}, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x1, ...})
        /usr/src/myapp/pkg/pipelines/delete_node.go:62 +0x8f
github.com/kubesphere/kubekey/cmd/ctl/delete.(*DeleteNodeOptions).Run(...)
        /usr/src/myapp/cmd/ctl/delete/delete_node.go:78
github.com/kubesphere/kubekey/cmd/ctl/delete.NewCmdDeleteNode.func1(0xc000153680, {0xc0004585f0, 0x5, 0x5})
        /usr/src/myapp/cmd/ctl/delete/delete_node.go:51 +0x1b8
github.com/spf13/cobra.(*Command).execute(0xc000153680, {0xc0004585a0, 0x5, 0x5})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005da280)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /usr/src/myapp/cmd/main.go:33 +0xe5
```

**Comment by 24sama** [comment]
Hi @hellocn9 thanks for your feedback.
I reproduced this bug.

/assign

**Comment by 24sama** [comment]
I create a PR to fix this issue. Welcome to review and test it.

/kind need-to-verify

**Comment by hellocn9** [comment]
Yes，with #1315 the problem solved. Great.
