### ISSUE TITLE
Kubekey panic when upgrading

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/kubekey#210]
KubeKey panic with below errors when upgrading 

Env:
CentOS 7
3 masters + 3 workers HA cluster
Kubernetes 1.14 => 1.17
KubeSphere 2.1.0 => 3.0.0
flannel + iptables
All components enabled

```
[master1] Downloading image: kubesphere/flannel:v0.12.0
[master2] Downloading image: kubesphere/flannel:v0.12.0
Push /root/kubekey/v1.15.12/amd64/kubeadm to 192.168.11.2:/tmp/kubekey/kubeadm  Done
Push /root/kubekey/v1.15.12/amd64/kubelet to 192.168.11.2:/tmp/kubekey/kubelet  Done
Push /root/kubekey/v1.15.12/amd64/kubectl to 192.168.11.2:/tmp/kubekey/kubectl  Done
Push /root/kubekey/v1.15.12/amd64/helm to 192.168.11.2:/tmp/kubekey/helm  Done
Push /root/kubekey/v1.15.12/amd64/cni-plugins-linux-amd64-v0.8.6.tgz to 192.168.11.2:/tmp/kubekey/cni-plugins-linux-amd64-v0.8.6.tgz  Done
E0816 18:38:34.163460  20585 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14f24e0, 0xc000366400)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14f24e0, 0xc000366400)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/kubesphere/kubekey/pkg/cluster/kubernetes/tmpl.GenerateKubeadmCfg(0xc0002b1a00, 0x21, 0xc000631400, 0x1, 0x1)
	/usr/src/myapp/pkg/cluster/kubernetes/tmpl/kubeadm.go:164 +0x1009
github.com/kubesphere/kubekey/pkg/upgrade.upgradeKubeMasters(0xc0002b1a00, 0xc00018d680, 0xc000121801, 0xc000405920)
	/usr/src/myapp/pkg/upgrade/kubernetes.go:134 +0xb93
github.com/kubesphere/kubekey/pkg/upgrade.upgradeCluster(0xc0002b1a00, 0xc00018d680, 0x7, 0xc00040c880)
	/usr/src/myapp/pkg/upgrade/kubernetes.go:270 +0x42
github.com/kubesphere/kubekey/pkg/util/manager.(*Manager).runTask(0xc0002b1a00, 0xc00018d680, 0x16a2d38, 0x0, 0xc00007a790, 0xc0002202a0)
	/usr/src/myapp/pkg/util/manager/task_run.go:56 +0x154
github.com/kubesphere/kubekey/pkg/util/manager.(*Manager).RunTaskOnNodes(0xc0002b1900, 0xc00018d680, 0x6, 0x8, 0x16a2d38, 0xc000152300, 0x0, 0x0)
	/usr/src/myapp/pkg/util/manager/task_run.go:100 +0x356
github.com/kubesphere/kubekey/pkg/util/manager.(*Manager).RunTaskOnK8sNodes(...)
	/usr/src/myapp/pkg/util/manager/task_run.go:145
github.com/kubesphere/kubekey/pkg/upgrade.UpgradeKubeCluster(0xc0002b1900, 0x0, 0x93f6af)
	/usr/src/myapp/pkg/upgrade/kubernetes.go:254 +0x46f
github.com/kubesphere/kubekey/pkg/util/manager.(*Task).Run.func1(0x0, 0x0, 0x0)
	/usr/src/myapp/pkg/util/manager/task_control.go:52 +0x4d
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc00033da88, 0xc00031e800, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x12a05f200, 0x4000000000000000, 0x0, 0x1, 0x0, 0xc000631a88, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:399 +0x55
github.com/kubesphere/kubekey/pkg/util/manager.(*Task).Run(0xc00033daf8, 0xc0002b1900, 0x0, 0x0)
	/usr/src/myapp/pkg/util/manager/task_control.go:48 +0xfa
github.com/kubesphere/kubekey/pkg/upgrade.ExecTasks(0xc0002b1900, 0xc0002b1900, 0x0)
	/usr/src/myapp/pkg/upgrade/upgrade.go:62 +0x1a0
github.com/kubesphere/kubekey/pkg/upgrade.Execute(0xc0000c5c80, 0xc, 0x7ffd7f47c6ff)
	/usr/src/myapp/pkg/upgrade/upgrade.go:87 +0x5c
github.com/kubesphere/kubekey/pkg/upgrade.UpgradeCluster(0x7ffd7f47c723, 0xc, 0x7ffd7f47c6ff, 0x7, 0x7ffd7f47c719, 0x6, 0xc000190000, 0x101, 0x15b95c3, 0x4)
	/usr/src/myapp/pkg/upgrade/upgrade.go:47 +0x23e
github.com/kubesphere/kubekey/cmd.glob..func6(0x2261ee0, 0xc000417320, 0x1, 0x6, 0x0, 0x0)
	/usr/src/myapp/cmd/upgrade.go:36 +0x1cc
github.com/spf13/cobra.(*Command).execute(0x2261ee0, 0xc0004172c0, 0x6, 0x6, 0x2261ee0, 0xc0004172c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x22619a0, 0x15c9c8b, 0x16, 0xc0000c5f20)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/kubesphere/kubekey/cmd.Execute()
	/usr/src/myapp/cmd/root.go:57 +0x31
main.main()
	/usr/src/myapp/kubekey.go:38 +0x1a5
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x14f24e0, 0xc000366400)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/kubesphere/kubekey/pkg/cluster/kubernetes/tmpl.GenerateKubeadmCfg(0xc0002b1a00, 0x21, 0xc000631400, 0x1, 0x1)
	/usr/src/myapp/pkg/cluster/kubernetes/tmpl/kubeadm.go:164 +0x1009
github.com/kubesphere/kubekey/pkg/upgrade.upgradeKubeMasters(0xc0002b1a00, 0xc00018d680, 0xc000121801, 0xc000405920)
	/usr/src/myapp/pkg/upgrade/kubernetes.go:134 +0xb93
github.com/kubesphere/kubekey/pkg/upgrade.upgradeCluster(0xc0002b1a00, 0xc00018d680, 0x7, 0xc00040c880)
	/usr/src/myapp/pkg/upgrade/kubernetes.go:270 +0x42
github.com/kubesphere/kubekey/pkg/util/manager.(*Manager).runTask(0xc0002b1a00, 0xc00018d680, 0x16a2d38, 0x0, 0xc00007a790, 0xc0002202a0)
	/usr/src/myapp/pkg/util/manager/task_run.go:56 +0x154
github.com/kubesphere/kubekey/pkg/util/manager.(*Manager).RunTaskOnNodes(0xc0002b1900, 0xc00018d680, 0x6, 0x8, 0x16a2d38, 0xc000152300, 0x0, 0x0)
	/usr/src/myapp/pkg/util/manager/task_run.go:100 +0x356
github.com/kubesphere/kubekey/pkg/util/manager.(*Manager).RunTaskOnK8sNodes(...)
	/usr/src/myapp/pkg/util/manager/task_run.go:145
github.com/kubesphere/kubekey/pkg/upgrade.UpgradeKubeCluster(0xc0002b1900, 0x0, 0x93f6af)
	/usr/src/myapp/pkg/upgrade/kubernetes.go:254 +0x46f
github.com/kubesphere/kubekey/pkg/util/manager.(*Task).Run.func1(0x0, 0x0, 0x0)
	/usr/src/myapp/pkg/util/manager/task_control.go:52 +0x4d
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc00033da88, 0xc00031e800, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x12a05f200, 0x4000000000000000, 0x0, 0x1, 0x0, 0xc000631a88, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:399 +0x55
github.com/kubesphere/kubekey/pkg/util/manager.(*Task).Run(0xc00033daf8, 0xc0002b1900, 0x0, 0x0)
	/usr/src/myapp/pkg/util/manager/task_control.go:48 +0xfa
github.com/kubesphere/kubekey/pkg/upgrade.ExecTasks(0xc0002b1900, 0xc0002b1900, 0x0)
	/usr/src/myapp/pkg/upgrade/upgrade.go:62 +0x1a0
github.com/kubesphere/kubekey/pkg/upgrade.Execute(0xc0000c5c80, 0xc, 0x7ffd7f47c6ff)
	/usr/src/myapp/pkg/upgrade/upgrade.go:87 +0x5c
github.com/kubesphere/kubekey/pkg/upgrade.UpgradeCluster(0x7ffd7f47c723, 0xc, 0x7ffd7f47c6ff, 0x7, 0x7ffd7f47c719, 0x6, 0xc000190000, 0x101, 0x15b95c3, 0x4)
	/usr/src/myapp/pkg/upgrade/upgrade.go:47 +0x23e
github.com/kubesphere/kubekey/cmd.glob..func6(0x2261ee0, 0xc000417320, 0x1, 0x6, 0x0, 0x0)
	/usr/src/myapp/cmd/upgrade.go:36 +0x1cc
github.com/spf13/cobra.(*Command).execute(0x2261ee0, 0xc0004172c0, 0x6, 0x6, 0x2261ee0, 0xc0004172c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x22619a0, 0x15c9c8b, 0x16, 0xc0000c5f20)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/kubesphere/kubekey/cmd.Execute()
	/usr/src/myapp/cmd/root.go:57 +0x31
main.main()
	/usr/src/myapp/kubekey.go:38 +0x1a5
```

**Comment by pixiake** [comment]
This panic is caused by an incomplete configuration file.

After generating the configuration file, some parameters need to be filled in, such as the ssh information of the nodes.
https://github.com/kubesphere/community/blob/master/sig-installation/kubekey/upgrade.md#multi-nodes-1

And we‘ll add some check for the configuration file.

**Comment by benjaminhuo** [comment]
ok, the upgrade could be resumed after filling in the missing etcd and controlplaneendpoint address field.
Yes, some instructions in upgrade docs is needed if there is no check in kubekey itself.

**Comment by benjaminhuo** [comment]
![image (12)](https://user-images.githubusercontent.com/18525465/90463359-57c4ee80-e13d-11ea-8c74-70175caa06fb.png)

Another problem is that the config file generated by kubeky for ks v2.1.0 upgrade contains imageRepo like:
`imageRepo: gcr.azk8s.cn/google-containers`

We'd better change it to `kubesphere` ?
