### ISSUE TITLE
Pipeline failed to rerun after upgrade

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#226]
![image](https://user-images.githubusercontent.com/22350668/90463687-26005780-e13e-11ea-8378-a4716bb47884.png)

![image](https://user-images.githubusercontent.com/22350668/90463701-2b5da200-e13e-11ea-9b14-3a46697ccb0a.png)

![image](https://user-images.githubusercontent.com/22350668/90463724-344e7380-e13e-11ea-96ec-e008d19254b6.png)

```
[Pipeline] kubernetesDeploy
Starting Kubernetes deployment
Loading configuration: /home/jenkins/agent/workspace/oject-Jp1ER9gr9yMl_git_sonarqube/deploy/dev-ol/devops-sample-svc.yaml
ERROR: ERROR: java.lang.RuntimeException: io.kubernetes.client.openapi.ApiException: Forbidden
hudson.remoting.ProxyException: java.lang.RuntimeException: io.kubernetes.client.openapi.ApiException: Forbidden
	at com.microsoft.jenkins.kubernetes.wrapper.ResourceManager.handleApiException(ResourceManager.java:193)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$ServiceUpdater.applyResource(V1ResourceManager.java:449)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$ServiceUpdater.applyResource(V1ResourceManager.java:379)
	at com.microsoft.jenkins.kubernetes.wrapper.ResourceManager$ResourceUpdater.createOrApply(ResourceManager.java:97)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.handleResource(KubernetesClientWrapper.java:289)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:256)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:172)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:124)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:106)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.233.99.236/10.233.99.236:33644
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.FilePath.act(FilePath.java:1160)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:68)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
Caused by: hudson.remoting.ProxyException: io.kubernetes.client.openapi.ApiException: Forbidden
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:979)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
	at io.kubernetes.client.openapi.apis.CoreV1Api.replaceNamespacedServiceWithHttpInfo(CoreV1Api.java:30741)
	at io.kubernetes.client.openapi.apis.CoreV1Api.replaceNamespacedService(CoreV1Api.java:30715)
	at com.microsoft.jenkins.kubernetes.wrapper.V1ResourceManager$ServiceUpdater.applyResource(V1ResourceManager.java:446)
	... 16 more
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (push with tag)
Stage "push with tag" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy to production)
Stage "deploy to production" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Kubernetes deployment ended with HasError
Finished: FAILURE
```

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/90486349-65916880-e16b-11ea-8a04-995e73232561.png)

![image](https://user-images.githubusercontent.com/43693241/90486381-6de9a380-e16b-11ea-884d-42b14d265bd1.png)

/assign @wansir

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
kubectl -n kubesphere-system rollout restart deploy
```

/kind need-to-verify

**Comment by huanggze** [comment]
not fixed @shaowenchen 

new error occurs

![image](https://user-images.githubusercontent.com/22350668/90853325-68c76700-e3ac-11ea-9bc4-4db048448dbe.png)

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/90855117-51d74380-e3b1-11ea-839b-1fa0b7380bc0.png)

I can't reproduce it.

**Comment by huanggze** [comment]
ok, verified
