### ISSUE TITLE
kk 安装集群报：panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ygqygq2** [kubesphere/kubekey#2482]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"1", GitVersion:"v3.1.7", GitCommit:"da475c670813fc8a4dd3b1312aaa36e96ff01a1f", GitTreeState:"clean", BuildDate:"2024-10-30T09:41:20Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Ubuntu 24.04

### A clear and concise description of what happend.

无法完成安装

### Relevant log output

```shell
19:08:13 CST command: [k8s-node04]
sudo -E /bin/bash -c "mv -f /tmp/kubekey/etc/systemd/system/kubelet.service.d/10-kubeadm.conf /etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
19:08:13 CST command: [k8s-node04]
sudo -E /bin/bash -c "rm -rf /tmp/kubekey/*"
19:08:13 CST success: [k8s-node01]
19:08:13 CST success: [k8s-master01]
19:08:13 CST success: [k8s-node03]
19:08:13 CST success: [k8s-node02]
19:08:13 CST success: [k8s-node04]
19:08:13 CST [InitKubernetesModule] Generate kubeadm config
19:08:13 CST command: [k8s-master01]
sudo -E /bin/bash -c "containerd config dump | grep SystemdCgroup || echo 'SystemdCgroup = false'"
19:08:13 CST stdout: [k8s-master01]
SystemdCgroup = true
19:08:13 CST pauseTag: 3.9, corednsTag: 1.9.3
19:08:13 CST pauseTag: 3.9, corednsTag: 1.9.3
19:08:13 CST pauseTag: 3.9, corednsTag: 1.9.3
19:08:13 CST pauseTag: 3.9, corednsTag: 1.9.3
19:08:13 CST pauseTag: 3.9, corednsTag: 1.9.3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98fe38]

goroutine 21742 [running]:
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/util.networkRange(0xc000c4b550?)
        github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/util/ip.go:121 +0x18
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/util.GetAvailableIP({0xc0000edc00?, 0xf?})
        github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/util/ip.go:79 +0x4a
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/util.ParseIp({0xc0000edc00?, 0xf?})
        github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/util/ip.go:40 +0xfd
github.com/kubesphere/kubekey/v3/cmd/kk/apis/kubekey/v1alpha2.(*ClusterSpec).GenerateCertSANs(0xc000775800)
        github.com/kubesphere/kubekey/v3/cmd/kk/apis/kubekey/v1alpha2/cluster_types.go:157 +0x2b8
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/kubernetes.(*GenerateKubeadmConfig).Execute(0xc000c643c0, {0x2890ed0, 0xc000ec36c0})
        github.com/kubesphere/kubekey/v3/cmd/kk/pkg/kubernetes/tasks.go:294 +0x14bb
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/task.(*RemoteTask).ExecuteWithRetry(0xc000556b40, {0x2890ed0, 0xc000ec36c0})
        github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/task/remote_task.go:216 +0x119
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/task.(*RemoteTask).Run(0xc000556b40, {0x2890ed0, 0xc000ec36c0}, {0x2897cb0, 0xc0004738d0}, 0x1e813fb?, 0x2?)
        github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/task/remote_task.go:152 +0x1c5
created by github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/task.(*RemoteTask).RunWithTimeout
        github.com/kubesphere/kubekey/v3/cmd/kk/pkg/core/task/remote_task.go:109 +0x16d
```

**Comment by ygqygq2** [comment]
解决了，config 里，我IP 写的不对。
