### ISSUE TITLE
segmentation Error when upgrade from v3.0.0 to v3.1.0 on centos7

### ISSUE THREAD

**Issue by pyfs** [kubesphere/kubekey#526]
As upgrade according to `https://kubesphere.io/zh/docs/upgrade/upgrade-with-kubekey/`

Error as below:

```shell
[root@master1 kubekey]# ./kk upgrade --with-kubernetes v1.20.4 --with-kubesphere v3.1.0 -f config-sample.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17db359]

goroutine 1 [running]:
github.com/kubesphere/kubekey/pkg/cluster/upgrade.UpgradeCluster(0x7ffefc77078f, 0x12, 0x7ffefc77076b, 0x7, 0x7ffefc770785, 0x6, 0xc0003c2000, 0xc000000101, 0x1b96a17, 0x10, ...)
	/home/runner/work/kubekey/kubekey/pkg/cluster/upgrade/upgrade.go:47 +0x1a9
github.com/kubesphere/kubekey/cmd.glob..func11(0x2e07fa0, 0xc00098c8a0, 0x1, 0x6, 0x0, 0x0)
	/home/runner/work/kubekey/kubekey/cmd/upgrade.go:36 +0x1f8
github.com/spf13/cobra.(*Command).execute(0x2e07fa0, 0xc00098c840, 0x6, 0x6, 0x2e07fa0, 0xc00098c840)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2e07a60, 0x0, 0x0, 0x2)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/kubesphere/kubekey/cmd.Execute()
	/home/runner/work/kubekey/kubekey/cmd/root.go:65 +0x125
main.main()
	/home/runner/work/kubekey/kubekey/cmd/kk/main.go:25 +0x20
```
---
Components Versions:

```text
[root@master1 kubekey]# ./kk version
version.BuildInfo{Version:"1.1.0", GitCommit:"70671f7", GitTreeState:"", GoVersion:"go1.14.15"}

[root@master1 kubekey]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

[root@master1 kubekey]# uname -r
3.10.0-1160.24.1.el7.x86_64
```

**Comment by 24sama** [comment]
duplicate #583
