### ISSUE TITLE
kk cannot recreate cluster

### ISSUE THREAD

**Issue by aeoluswing** [kubesphere/kubekey#587]
I've installed kubesphere and kubernetes on my cluster which contains 7 server nodes.Sometime ago,I deleted kubesphere namespace by mistake.I removed kubesphere and kubernetes manually and rm docker directory.After that rerun command `./kk create cluster -f config-sample.yaml` but got some error below:

```shell
./kk create cluster -f config-sample.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x17c4bcd]

goroutine 1 [running]:
github.com/kubesphere/kubekey/pkg/cluster/install.CreateCluster(0x7ffd13622eaf, 0x12, 0x0, 0x0, 0x0, 0x0, 0xc0005a4310, 0x100, 0x1b97b0b, 0x10, ...)
        /home/runner/work/kubekey/kubekey/pkg/cluster/install/install.go:56 +0x1cd
github.com/kubesphere/kubekey/cmd.glob..func2(0x2e0bd20, 0xc000e80e40, 0x0, 0x2, 0x0, 0x0)
        /home/runner/work/kubekey/kubekey/cmd/cluster.go:40 +0x237
github.com/spf13/cobra.(*Command).execute(0x2e0bd20, 0xc000e80e20, 0x2, 0x2, 0x2e0bd20, 0xc000e80e20)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2e0aac0, 0x0, 0x0, 0x2)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/kubesphere/kubekey/cmd.Execute()
        /home/runner/work/kubekey/kubekey/cmd/root.go:65 +0x125
main.main()
        /home/runner/work/kubekey/kubekey/cmd/kk/main.go:25 +0x20
```

I've no idea what this panic happened, and what does `invalid memory address` exactly mean? Any suggestions are appreciated

**Comment by 24sama** [comment]
Can you paste your `config-sample.yaml` in here?
